# 1.3: Virtual Environments in Python
Kernel = 20th_century

In [1]:
# Import Libraries
import pandas as pd

In [5]:
# Random Data
data = pd.DataFrame({"Country": ['Mexico', 'Japan', 'Italy','USA'],
                     "Food": ["Tacos", "Sushi", "Pizza", "Hamburger"],
                     "Price": [3,12,10,11]})

In [9]:
data

  Country       Food  Price
0  Mexico      Tacos      3
1   Japan      Sushi     12
2   Italy      Pizza     10
3     USA  Hamburger     11

In [11]:
# mathematical procedure using a lambda function
multiply = lambda x: x*10
multiply(data['Price'])

0     30
1    120
2    100
3    110
Name: Price, dtype: int64

In [13]:
# flag column
data['Price_Level'] = data['Price'].apply(
lambda x:  'high' if x > 10 else ('normal' if x >=5 else 'low'))

In [15]:
data

  Country       Food  Price Price_Level
0  Mexico      Tacos      3         low
1   Japan      Sushi     12        high
2   Italy      Pizza     10      normal
3     USA  Hamburger     11        high